#!/bin/sh

usage() {
    echo "Usage: $0 <os-platform>"
    exit 1
}

check_require() {
	if  hash gcc 2>/dev/null; then
    	echo 'gcc:' `gcc -dumpversion`
	else
		echo 'Not found C compile, exit.'
	    exit 1
	fi
	
	if  hash node 2>/dev/null; then
	    echo 'node:' `node -v`
	else
	    sudo apt-get install nodejs
	fi
	
	if  hash npm 2>/dev/null; then
	    echo 'npm:' `npm -v`
	else
	    apt-get install npm
	fi
	
	if  hash node-gyp 2>/dev/null; then
	    echo 'node-gyp:' `node-gyp -v`
	else
	    npm install nan node-gyp -g
	fi
}

if [ $# -ne 1 ]; then
    usage $*
fi

check_require

PRO_DIR=$(pwd)
if [ ! -d  $PRO_DIR/objs ]; then
    mkdir $PRO_DIR/objs
fi

if [ ! -d  $PRO_DIR/srs-librtmp ]; then
    git clone https://github.com/aesirteam/srs-librtmp.git
fi

cd live555/liveMedia
rm -f Makefile
cat Makefile.head $PRO_DIR/config.$1 Makefile.tail > Makefile

cd ../groupsock
rm -f Makefile
cat Makefile.head $PRO_DIR/config.$1 Makefile.tail > Makefile

cd ../UsageEnvironment
rm -f Makefile
cat Makefile.head $PRO_DIR/config.$1 Makefile.tail > Makefile

cd ../BasicUsageEnvironment
rm -f Makefile
cat Makefile.head $PRO_DIR/config.$1 Makefile.tail > Makefile

cd $PRO_DIR/srs-librtmp
rm -f Makefile
cat Makefile.tail > Makefile

cd objs
rm -f Makefile
cat $PRO_DIR/config.$1 Makefile.tail > Makefile

cd $PRO_DIR
rm -f Makefile
cat Makefile.head config.$1 Makefile.tail > Makefile

cd src
rm -f Makefile
cat $PRO_DIR/config.$1 Makefile.tail > Makefile

cd $PRO_DIR/node-gyp
rm -f Makefile
cat $PRO_DIR/config.$1 Makefile.tail > Makefile
